-- IMPORT  source d:\xampp\htdocs\BDProject\databaseInit.sql --

DROP DATABASE IF EXISTS `CMS_HUB`;

CREATE DATABASE IF NOT EXISTS `CMS_HUB` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE CMS_HUB;
CREATE TABLE IF NOT EXISTS USERS
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
    loginU VARCHAR(100),
    password VARCHAR(128),
    isActive BOOLEAN,
    homeDirectory VARCHAR(255),
    permission TINYINT,
    website_ID INTEGER,
    created_at DATETIME
);

CREATE INDEX IF NOT EXISTS USERS_INDEX
ON USERS (ID, loginU, website_ID);

-- SUBTABLE OF USERS--

CREATE TABLE IF NOT EXISTS FILEREGISTER
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
    ID_user INTEGER,
    rootPath VARCHAR(255),
    typeFile VARCHAR(255),
    type_mime VARCHAR(120),
    size INTEGER,
    pathFile VARCHAR(255),
    created_at DATETIME,
    modified_at DATETIME
);

CREATE INDEX IF NOT EXISTS FILEREGISTER_INDEX
ON FILEREGISTER (ID, ID_user, pathFile);

CREATE TABLE IF NOT EXISTS LOGI
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
    ID_user INTEGER,
    ID_website INTEGER,
    content VARCHAR(255),
    created_at DATETIME
);

CREATE TABLE IF NOT EXISTS WEBSITES
(
    ID_website INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
    title_website VARBINARY(300),
    shortcut_icon_path VARBINARY(255),
    ID_user INTEGER,
    isActive BOOLEAN,
    ID_settings INTEGER,
    created_at DATETIME,
    modified_at DATETIME
);

CREATE INDEX IF NOT EXISTS WEBSITES_INDEX
ON WEBSITES (ID_website, ID_user);

-- SUBTABLES WEBSITES--
CREATE TABLE IF NOT EXISTS SETTINGS
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
    PHP_version VARCHAR(255),
    limit_upload_file_size INTEGER,
    contact VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CONTENT
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
    page_ID INTEGER,
    content VARBINARY(2000),
    role_section VARCHAR(255),
    order INTEGER
);

CREATE INDEX IF NOT EXISTS CONTENT_INDEX
ON CONTENT (ID, page_ID);

CREATE TABLE IF NOT EXISTS PAGESWEB
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
    Menu_ID INTEGER,
    Theme_ID INTEGER,
    ID_website INTEGER,
    Title VARCHAR(80),
    keyphrases VARCHAR(70),
    description_meta VARCHAR(155),
    content VARBINARY(2000),
    footerText VARBINARY(500)
);

-- PAGESWEB SUBTABLES --
CREATE TABLE IF NOT EXISTS THEME
(
    ID INTEGER PRIMARY KEY UNIQUE AUTO_INCREMENT,
    customFields VARBINARY(2000)
);

CREATE TABLE IF NOT EXISTS MODULES
(
    ID INTEGER PRIMARY KEY UNIQUE AUTO_INCREMENT,
    moduleName VARCHAR(255),
    ID_file INTEGER,
    roleModule VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS MODULES_THEMES
(
    ID PRIMARY KEY UNIQUE AUTO_INCREMENT,
    ID_MODULE INTEGER,
    ID_THEME INTEGER
);

CREATE TABLE IF NOT EXISTS MENU
(
    ID INTEGER PRIMARY KEY UNIQUE AUTO_INCREMENT,
    level_menu INTEGER
);

CREATE TABLE IF NOT EXISTS LIST_ITEM
(
    ID INTEGER PRIMARY KEY UNIQUE AUTO_INCREMENT,
    ID_menu INTEGER,
    textLink VARCHAR(255),
    href VARBINARY(400),
    depth INTEGER,
    order INTEGER
);

-- Foreign keys
ALTER TABLE USERS
ADD CONSTRAINT FK_userswebsites 
FOREIGN KEY (website_ID) REFERENCES WEBSITES(ID_website);

ALTER TABLE FILEREGISTER
ADD CONSTRAINT FK_fileregisterusers
FOREIGN KEY (ID_user) REFERENCES USERS(ID);

ALTER TABLE LOGI
ADD CONSTRAINT FK_logiusers
FOREIGN KEY (ID_user) REFERENCES USERS(ID);

ALTER TABLE LOGI
ADD CONSTRAINT FK_logiwebsites
FOREIGN KEY (ID_website) REFERENCES WEBSITES(ID_website);

ALTER TABLE WEBSITES
ADD CONSTRAINT FK_websitesusers
FOREIGN KEY (ID_user) REFERENCES USERS(ID);

ALTER TABLE WEBSITES
ADD CONSTRAINT FK_websitessettings
FOREIGN KEY (ID_settings) REFERENCES SETTINGS(ID);

ALTER TABLE CONTENT
ADD CONSTRAINT FK_contentpagesweb
FOREIGN KEY (page_ID) REFERENCES PAGESWEB(ID);

ALTER TABLE PAGESWEB
ADD CONSTRAINT FK_pageswebmenu
FOREIGN KEY (Menu_ID) REFERENCES MENU(ID);

ALTER TABLE PAGESWEB
ADD CONSTRAINT FK_pageswebtheme
FOREIGN KEY (Theme_ID) REFERENCES THEME(ID);

ALTER TABLE PAGESWEB
ADD CONSTRAINT FK_pageswebwebsites
FOREIGN KEY (ID_website) REFERENCES WEBSITES(ID_website);

ALTER TABLE MODULES
ADD CONSTRAINT FK_modulesfileregister 
FOREIGN KEY (ID_file) REFERENCES FILEREGISTER(ID);

ALTER TABLE MODULES_THEMES
ADD CONSTRAINT FK_modulesthemesmodules
FOREIGN KEY (ID_MODULE) REFERENCES MODULES(ID_MODULE);

ALTER TABLE MODULES_THEMES
ADD CONSTRAINT FK_modulesthemesthemes
FOREIGN KEY (ID_THEME) REFERENCES THEMES(ID);

ALTER TABLE LIST_ITEM
ADD CONSTRAINT FK_listItemMenu
FOREIGN KEY (ID_menu) REFERENCES MENU(ID);